# Generated by Django 5.1.5 on 2025-01-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subSummarize', '0003_auto_20181023_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='videoDwldURL',
            field=models.CharField(default='https://youtu.be/Hd5uiln4ImM?si=17eUFggoQkuJHjPL', max_length=100),
        ),
    ]
